name = "serpbear"
compatibility_date = "2024-04-11"
pages_build_output_dir = "./dist"

[site]
bucket = "./out"
entry-point = "./"

[[r2_buckets]]
binding = "R2_SERPBEAR"
bucket_name = "serpbear"

[[d1_databases]]
binding = "R1_SERPBEAR"
database_name = "serpbear"


# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
